### ISSUE TITLE
Custom upload location

### ISSUE THREAD

**Issue by atifarkas** [nsg/immich-distribution#35]
### Question

This is great stuff for lazy man as me, but I would like to store images on harddisk and using ssd for system. How can I change /var/snap/immich-distribution/common/upload/ path to another harddisk?

**Comment by nsg** [comment]
We need to consider the sandbox, the snap can currently only write to `/var/snap/immich-distribution/` so the easiest solution is to mount another partition (on your larger harddisk) directly over `/var/snap/immich-distribution/common/upload/`. Make sure that permissions are correct.

A more clean "snap way" to solve this is for me to expose the `removable-media` interface, and add a option to move the upload location to `/media/...` or `/mnt/...` so you can access other your larger harddisk directly. This assumes that your larger harddisk is mounted on one of these default locations.

If your harddisk is mounted on a non-standard location, or, if you do not have a dedicated partition. Mount binds should work, with that you should be able to "bind" any folder like `/foo/bar` to `/var/snap/immich-distribution/common/upload/`.

It's common to have `/var/snap/` on a smaller drive (like a ssd) so I will think about a good way to integrate this with Immich Distribution. Thank you for your feedback!

**Comment by nsg** [comment]
I have documented the process here https://immich-distribution.nsg.cc/configuration/storage/

I choose to recommend bind mount because there are much more flexible. The `removable-media` has a lot of limitations, and it would be tricky for me to test it for future releases and I'm afraid it would cause problems in the future. I like to keep Immich Distribution easy to maintain and test, upstream Immich releases like crazy so I need to keep up :)

Feel free to comment in this issue, or open a new one if you have questions or like to add something. I hope this works for you!
